name: evaluacion_estudiantil
description: Proyecto de notas
version: 1.0.0

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  fl_chart: ^0.70.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



